### ISSUE TITLE
Images Gulp task references source files with .scss extension

### ISSUE THREAD

**Issue by johnpeele** [planetary/airframe#3]
I was just browsing the Gulp tasks in prep to use Airframe for the first time and noticed this:

`gulp.watch( 'src/img/**/*.scss', [ 'images' ] );`

Doesn't seem right, but I could be overlooking something. Apologies if I have ;)

**Comment by endtwist** [comment]
You are very correct, thanks! We just pushed a fix at d37bf54fb565d66547a533a4554eb1e69df830be, and bumped to v1.0.0 because flexbox :)
